[package]
name = "q_2"
version = "0.1.0"
authors = ["Maliha <maliha.babar97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
